#
# This file is autogenerated during plugin quickstart and overwritten during
# plugin makedist. DO NOT CHANGE IT if you plan to use plugin makedist to update 
# the distribution.
#

from setuptools import setup, find_packages

kwargs = {'author': 'Caitlin Kavenaugh',
 'author_email': '',
 'classifiers': ['Intended Audience :: Science/Research',
                 'Topic :: Scientific/Engineering'],
 'description': 'OpenMDAO wrapper for a Feedforward Neural Net surrogate model that can be slotted into the MetaModel component',
 'download_url': '',
 'entry_points': '[openmdao.surrogatemodel]\nneural_net.neural_net.NeuralNet=neural_net.neural_net:NeuralNet\n\n[openmdao.container]\nneural_net.neural_net.NeuralNet=neural_net.neural_net:NeuralNet',
 'include_package_data': True,
 'install_requires': ['openmdao.main', 'ffnet'],
 'keywords': ['openmdao'],
 'license': 'GNU General Public License, version 2',
 'maintainer': 'Kenneth T. Moore',
 'maintainer_email': 'kenneth-t-mooore-1@nasa.gov',
 'name': 'neural_net',
 'package_data': {'neural_net': []},
 'package_dir': {'': 'src'},
 'packages': ['neural_net'],
 'url': 'https://github.com/OpenMDAO-Plugins/neural_net',
 'version': '0.6',
 'zip_safe': False}


setup(**kwargs)

